### ISSUE TITLE
Similarly names branches can cause "Sequence contains more than one matching element" error

### ISSUE THREAD

**Issue by Bebo2345** [jessehouwing/tfstools#1]
If a branch starts with and contains the name of another branch, a "Sequence contains more than one matching element" error will occur.

For example the following branches will cause this error:

> $/MyProject/Production/1.0
> $/MyProject/Production/1.0.1

**Comment by jessehouwing** [comment]
Thanks for the feedback, I've published a new version which uses a more sophisticated way of tracking child to parent :).

**Comment by Bebo2345** [comment]
Excellent! Thank you! I cut corners in my version and just appended a "/" before doing the StartsWith comparison. Your solution is more robust! :-)

**Comment by jessehouwing** [comment]
Glad to know I created this for more than just me :)
